apiVersion: v1
kind: Pod
metadata:
  name: test-app
  namespace: dev
spec:
  containers:
  - name: app
    image: jenkins-cloud-native-app:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 8080
